### ISSUE TITLE
Dropbox integration broken

### ISSUE THREAD

**Issue by hetas** [pycage/cargodock#11]
Dropbox integration is broken.

I assume it's because app uses v1 api witch isn't supported any more, see https://blogs.dropbox.com/developers/2016/06/api-v1-deprecated/

**Comment by pycage** [comment]
Yes, we need to support the new API. Patches are welcome. :)

**Comment by Wedmer** [comment]
Difference between v1 and v2 API is huge. I afraid that at least a half of internal dropboxapi library should be rewritten. No ETA for now but I started this process.

**Comment by pycage** [comment]
Cool, thanks! Will you send a pull-request?

**Comment by Wedmer** [comment]
I've merged your ftp branch to my devel branch. After that I've merged my devel to master. Is this ok?

**Comment by Wedmer** [comment]
Latest build can be downloaded from openrepos.
