### ISSUE TITLE
Abandoned project

### ISSUE THREAD

**Issue by Wedmer** [pycage/cargodock#12]
As about 2 years passed after latest commit can we count this project as abandoned?

**Comment by pycage** [comment]
Hi,
it's true that this project is currently in hibernation and I'm not certain about its future. I have some plans like FTP support and reworked UI, which are both started already, but take more time to finish than I can spend on the project at the moment. Support for the new Dropbox API is another open issue.
I have noticed that you forked the project. If you want to work on CargoDock, please do so.

**Comment by Wedmer** [comment]
Thanks for reply.
