### ISSUE TITLE
Translation not working

### ISSUE THREAD

**Issue by ensag-dev** [pycage/cargodock#33]
Hello,
the French file doesn't seem to be recognised, the app stays in English.

**Comment by Wedmer** [comment]
Ok, I'll check. Anyway it's not complete

**Comment by ensag-dev** [comment]
Yes but main texts are covered ^^

**Comment by Wedmer** [comment]
Can you provide contents of LC_ALL and LANG environment variables?

**Comment by ensag-dev** [comment]
The ISO code for French would be "fr", is what you need?

**Comment by Wedmer** [comment]
Just need to know how env should be set for debug. Also, can you provide which version do you use? From Harbour or from open-repos?

**Comment by ensag-dev** [comment]
Yes I took it from open-repos. I've just tried, from Harbour I have the same behaviour.

**Comment by Wedmer** [comment]
Version at harbour doesn't have any translations. Just checked installed files. Mysteriously there's no translation file for French locale. Will be fixed on next release.

**Comment by ensag-dev** [comment]
Many thanks :) I'll try to translate more strings if I have time!

**Comment by Wedmer** [comment]
@ensag-dev Please check if it works in a new version.

**Comment by Wedmer** [comment]
No feedback
